sed -i 's/label/mylabel/g' $1 
sed -i 's/label/mylabel/g' $2
sed -i 's/label/mylabel/g' $3 
sed -i 's/label/mylabel/g' $4
sed -i 's/label/mylabel/g' $5
sed -i 's/label/mylabel/g' $6
sed -i 's/label/mylabel/g' $7
sed -i 's/label/mylabel/g' $8
sed -i 's/label/mylabel/g' $9
